title: Configuration
type: object
properties:
    client_ids:
        type: array
        items:
            description: Allowed client IDs
            type: string
    folder:
        type: string
        default : "images/"
        description: Image storage path
    port:
        type: integer
        default : 8080
        description: Port to bind to
    host:
        type: string
        default: localhost
        description: IP address to bind to
required:
    - client_ids
    - folder
additionalProperties: False