[tool.isort]
profile = "black"
skip = "gobgp_bindings"

[tool.black]
line-length = 100
exclude = "gobgp_bindings"

[tool.poetry]
name = "anastasia"
version = "1.0.3"
description = ""
authors = ["Marco Marzetti <marco@lamehost.it>"]
readme = "README.md"
packages = [{include = "anastasia"}]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.16.0"
fastapi = ">=0.9.0"
email-validator = "^1.1.3"
python-multipart = "^0.0.5"
pytest = "^7.2.0"
black = "^23.3.0"
pydantic = "<2.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.9"
coverage = "^7.0.1"
flake8 = "^6.0.0"
requests = "^2.28.1"
httpx = "^0.23.1"

[tool.poetry.scripts]
anastasia = "anastasia.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
