[tool.isort]
profile = "black"

[tool.black]
line-length = 100

[tool.poetry]
name = "anastasia"
version = "1.0.4"
description = ""
authors = ["Marco Marzetti <marco@lamehost.it>"]
readme = "README.md"
packages = [{include = "anastasia"}]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.16.0"
fastapi = ">=0.9.0"
email-validator = "^1.1.3"
python-multipart = "^0.0.7"
pytest = "^7.2.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.9"
coverage = "^7.0.1"
flake8 = "^6.0.0"
requests = "^2.32.0"
httpx = "^0.23.1"
black = "^24.3.0"
pydantic = "<2.0"
bandit = "^1.7.7"

[tool.poetry.scripts]
anastasia = "anastasia.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
